#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_in = 3
    gaps_out = 10
    border_size = 1

    col.active_border = rgba(cc0000ee) rgba(ffbf00ee) 45deg
    col.inactive_border = rgba(1a0000aa)

    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 0
    rounding_power = 2

    active_opacity = 1.0
    inactive_opacity = 0.97

    shadow {
        enabled = true
        range = 8
        render_power = 2
        color = rgba(cc000033)
    }

    blur {
        enabled = true
        size = 4
        passes = 2
        vibrancy = 0.2
        new_optimizations = true
    }
}

animations {
    enabled = yes, please :)

    bezier = easeOutQuint,0.23,1,0.32,1
    bezier = easeInOutCubic,0.65,0.05,0.36,1
    bezier = linear,0,0,1,1
    bezier = almostLinear,0.5,0.5,0.75,1.0
    bezier = quick,0.15,0,0.1,1
    bezier = snap,0.19,1,0.22,1

    animation = global, 1, 10, default
    animation = border, 1, 3, easeOutQuint
    animation = windows, 1, 3.5, snap
    animation = windowsIn, 1, 3, snap, popin 80%
    animation = windowsOut, 1, 1.2, linear, popin 80%
    animation = fadeIn, 1, 2, almostLinear
    animation = fadeOut, 1, 1.5, almostLinear
    animation = fade, 1, 2.5, quick
    animation = layers, 1, 3, easeOutQuint
    animation = layersIn, 1, 3, snap, fade
    animation = layersOut, 1, 1.2, linear, fade
    animation = fadeLayersIn, 1, 1.5, almostLinear
    animation = fadeLayersOut, 1, 1.2, almostLinear
    animation = workspaces, 1, 2.5, snap, slide
    animation = workspacesIn, 1, 2.5, snap, slide
    animation = workspacesOut, 1, 2, quick, slide
}

dwindle {
    pseudotile = true
    preserve_split = true
    smart_split = true
    smart_resizing = true
}

master {
    new_status = master
}

misc {
    font_family = "JetBrains Mono"
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    allow_session_lock_restore = true
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
}
